version: '2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: elasticsearch
    ports:
      - 127.0.0.1:9200:9200
    environment:
      - bootstrap.memory_lock=true
      - xpack.monitoring.collection.interval=60s
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - esnet
    mem_limit: 1g
    restart: always
 
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.2
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - xpack.monitoring.min_interval_seconds=60s
    networks:
      - esnet
    depends_on:
      - elasticsearch
    mem_limit: 256m
    restart: always

  logstash:
    image: docker.elastic.co/logstash/logstash:6.4.2
    container_name: logstash
    ports:
      - 127.0.0.1:5044:5044
    environment:
      - "LS_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - lspipelines:/usr/share/logstash/pipeline
    networks:
      - esnet
    depends_on:
      - elasticsearch
    mem_limit: 512m
    restart: always

volumes:
  esdata:
    driver: local
  lspipelines:
    driver: local

networks:
  esnet:
